# Generated by Django 5.0.6 on 2024-06-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
